// This script is not included in the package, but since we
// require version.js to exist and to be built inside this package,
// we must build it prior to npm publish.
require('fs').writeFileSync('./version.js', [
    '// This file was auto-generated by _prepublish.js',
    'export default {',
    '   git: false,',
    '   SHA: {},',
    '   shortSHA: {},',
    `   date: '${new Date().toISOString()}',`,
    `   apiVersion: '${require('./package.json').version}'`,
    '};'
].join('\n') + '\n');
