reporting:
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
    report-config:
        cobertura: {file: js_coverage.xml}
        lcovonly: {file: lcov.info}
