slicer.views.ControlWidget = girder.View.extend({
    events: {
        'change input,select': '_input',
        'changeColor': '_input',
        'click .s-select-file-button': '_selectFile'
    },

    initialize: function () {
        this.listenTo(this.model, 'change', this.render);
        this.listenTo(this.model, 'destroy', this.remove);
        this.listenTo(this.model, 'invalid', this.invalid);
    },

    render: function (_, options) {
        this.$('.form-group').removeClass('has-error');
        this.model.isValid();
        if (options && options.norender) {
            return this;
        }
        this.$el.html(this.template()(this.model.attributes));
        this.$('.s-control-item[data-type="range"] input').slider();
        this.$('.s-control-item[data-type="color"] .input-group').colorpicker({});
        return this;
    },

    remove: function () {
        this.$('.s-control-item[data-type="color"] .input-group').colorpicker('destroy');
        this.$('.s-control-item[data-type="range"] input').slider('destroy');
        this.$el.empty();
    },

    /**
     * Set classes on the input element to indicate to the user that the current value
     * is invalid.  This is automatically triggered by the model's "invalid" event.
     */
    invalid: function () {
        this.$('.form-group').addClass('has-error');
    },

    /**
     * Type definitions mapping used internally.  Each widget type
     * specifies it's jade template and possibly more custimizations
     * as needed.
     */
    _typedef: {
        range: {
            template: 'rangeWidget'
        },
        color: {
            template: 'colorWidget'
        },
        string: {
            template: 'widget'
        },
        number: {
            template: 'widget'
        },
        boolean: {
            template: 'booleanWidget'
        },
        'string-vector': {
            template: 'widget'
        },
        'number-vector': {
            template: 'widget'
        },
        'string-enumeration': {
            template: 'enumerationWidget'
        },
        'number-enumeration': {
            template: 'enumerationWidget'
        },
        file: {
            template: 'fileWidget'
        },
        image: {
            template: 'fileWidget'
        },
        directory: {
            template: 'fileWidget'
        },
        'new-file': {
            template: 'fileWidget'
        }
    },

    /**
     * Get the appropriate template for the model type.
     */
    template: function () {
        var type = this.model.get('type');
        var def = this._typedef[type];

        if (def === undefined) {
            console.warn('Invalid widget type "' + type + '"'); // eslint-disable-line no-console
            def = {};
        }
        return slicer.templates[def.template] || _.template('');
    },

    /**
     * Get the current value from an input (or select) element.
     */
    _input: function (evt) {
        var $el, val;

        $el = $(evt.target);
        val = $el.val();

        if ($el.attr('type') === 'checkbox') {
            val = $el.get(0).checked;
        }

        // we don't want to rerender, because this event is generated by the input element
        this.model.set('value', val, {norender: true});
    },

    /**
     * Get the value from a file selection modal and set the text in the widget's
     * input element.
     */
    _selectFile: function () {
        var modal = new slicer.views.ItemSelectorWidget({
            el: $('#g-dialog-container'),
            parentView: this,
            model: this.model
        });
        modal.once('g:saved', _.bind(function () {
            modal.$el.modal('hide');
        }, this)).render();
    }
});
