---

- name: Install Girder system dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_user: root
  with_items:
    - git
    - libffi-dev
    - build-essential
    - python2.7-dev
    - python-pip
    - libjpeg-dev
    - zlib1g-dev

# The following 3 steps are are necessary for VirtualBox with Ubuntu 14.04, as
# packaged Girder cannot be built with Python<2.7.9 on VirtualBox's filesystem
# (Python Issue #8876)
# TODO: these steps should be optional
- name: Add Python Updates PPA key
  apt_key:
    id: "DB82666C"
    keyserver: "keyserver.ubuntu.com"
  become: yes
  become_user: root

- name: Add Python Updates PPA
  apt_repository:
    repo: "deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main"
  become: yes
  become_user: root

- name: Install updated Python
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  become_user: root
  with_items:
    - python2.7
    - python2.7-dev

- name: Update Pip
  pip:
    name: pip
    state: latest
  become: yes
  become_user: root

- name: Download Girder
  git:
    repo: "https://github.com/girder/girder.git"
    dest: "{{ girder_path }}"
    version: "{{ girder_version }}"
    update: "{{ girder_update|default(omit) }}"
    force: "{{ girder_force|default(omit) }}"
  notify: Build Girder

- name: Install Girder Python requirements
  pip:
    requirements: "{{ girder_path }}/requirements.txt"
  become: yes
  become_user: root

- name: Install Girder and plugin requirements
  pip:
    name: ".[plugins]"
    editable: yes
    chdir: "{{ girder_path }}"
  become: yes

- name: Run npm install
  command: "npm install --production"
  args:
    chdir: "{{ girder_path }}"
