---
- name: Converge
  hosts: targets
  vars:
    girder_module_virtualenv: "{{ ansible_user_dir }}/.virtualenvs/girder_module"
  pre_tasks:
    - name: Install girder client
      pip:
        name: girder-client
        extra_args: "--pre"
        virtualenv: "{{ girder_module_virtualenv }}"
        virtualenv_command: "/usr/bin/python3 -m venv"
    - name: Wait for Girder to be listening
      wait_for:
        port: 8080
        host: "localhost"
  tasks:
    - include_tasks: "{{ item }}"
      with_fileglob:
        - "test_*.yml"
      vars:
        ansible_python_interpreter: "{{ girder_module_virtualenv }}/bin/python3"
