---

- hosts: all
  vars:
    girder_update: no
    girder_force: no
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
      become_user: root

  roles:
    - girder

  post_tasks:
    - name: Install Grunt globally
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - grunt
        - grunt-cli
      become: yes
      become_user: root

    - name: Install Girder Python development requirements
      pip:
        requirements: "requirements-dev.txt"
        chdir: "/home/vagrant/girder"
      become: yes
      become_user: root

    - name: Build Girder with development dependencies
      command: "npm install"
      args:
        chdir: "/home/vagrant/girder"
